"""Stage 5: Generate ``reports/data_quality.md`` from the processed parquets.

For each split, per-dataset statistics:
  - row count
  - missing-value counts per schema column
  - text length stats (chars & whitespace-token count)
  - label distributions (emotion_label top-10, topic top-5)
  - ``crisis_flag`` count and ``crisis_source`` breakdown
  - duplicate ``text`` count (warns if >5%)

Critical issues raise at the end so CI / smoke-tests catch them.
"""

from __future__ import annotations

from collections import Counter
from pathlib import Path

import pandas as pd

from .config import PROCESSED_DIR, REPORTS_DIR, SCHEMA_COLUMNS, processed_path, report_path


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _token_count(s: str) -> int:
    if not isinstance(s, str):
        return 0
    return len(s.split())


def _missing_value_summary(df: pd.DataFrame) -> pd.Series:
    return df.isna().sum()


def _label_top(df: pd.DataFrame, col: str, n: int = 10) -> list[tuple[str, int]]:
    if col not in df.columns:
        return []
    series = df[col].dropna().astype(str)
    series = series[series.str.strip() != ""]
    if series.empty:
        return []
    return Counter(series).most_common(n)


def _per_dataset_stats(df: pd.DataFrame) -> dict[str, object]:
    """Aggregate stats for a single DataFrame (per-dataset slice)."""
    text = df["text"].astype(str)
    char_lens = text.str.len()
    tok_lens = text.apply(_token_count)

    crisis = df["crisis_flag"].fillna(False).astype(bool)
    crisis_source_counter = Counter(
        df.loc[crisis, "crisis_source"].dropna().astype(str).tolist()
    )

    return {
        "row_count": int(len(df)),
        "missing": _missing_value_summary(df).to_dict(),
        "text_char_len": {
            "mean": float(char_lens.mean()) if len(char_lens) else 0.0,
            "p50": float(char_lens.median()) if len(char_lens) else 0.0,
            "p95": float(char_lens.quantile(0.95)) if len(char_lens) else 0.0,
            "max": int(char_lens.max()) if len(char_lens) else 0,
        },
        "text_token_len": {
            "mean": float(tok_lens.mean()) if len(tok_lens) else 0.0,
            "p95": float(tok_lens.quantile(0.95)) if len(tok_lens) else 0.0,
            "max": int(tok_lens.max()) if len(tok_lens) else 0,
        },
        "emotion_label_top": _label_top(df, "emotion_label", n=10),
        "emotion_labels_top": _label_top_multi(df, "emotion_labels", n=10),
        "topic_top": _label_top(df, "topic", n=5),
        "crisis_flag_count": int(crisis.sum()),
        "crisis_source_breakdown": crisis_source_counter.most_common(10),
        "duplicates": 0,
        "duplicate_pct": 0.0,
    }


def _label_top_multi(df: pd.DataFrame, col: str, n: int) -> list[tuple[str, int]]:
    """For comma-separated multi-label columns (GoEmotions)."""
    if col not in df.columns:
        return []
    counter: Counter[str] = Counter()
    for value in df[col].dropna().astype(str):
        for label in value.split(","):
            label = label.strip()
            if label:
                counter[label] += 1
    return counter.most_common(n)


def _duplicate_stats(df: pd.DataFrame) -> tuple[int, float]:
    if df.empty:
        return 0, 0.0
    dup = int(df["text"].duplicated().sum())
    return dup, dup / len(df)


# ---------------------------------------------------------------------------
# Report generation
# ---------------------------------------------------------------------------

def _md_section(title: str, body: str, level: int = 2) -> str:
    return f"\n{'#' * level} {title}\n\n{body}\n"


def _fmt_int(n: int) -> str:
    return f"{n:,}"


def _build_report(per_split: dict[str, dict[str, dict]]) -> str:
    lines: list[str] = []
    lines.append("# mindcare-ai — Data Quality Report\n")
    lines.append(
        "Auto-generated by `src/data_pipeline/validate.py`. "
        "Statistics are computed over the processed parquets in "
        f"`{PROCESSED_DIR.relative_to(Path.cwd()) if Path.cwd() in PROCESSED_DIR.parents else PROCESSED_DIR}`.\n"
    )

    # Summary table.
    lines.append("## Summary\n")
    lines.append("| Split | Total rows | Crisis-flagged | Crisis % | Duplicates | Dup % |")
    lines.append("|-------|-----------:|---------------:|---------:|-----------:|------:|")
    for split, datasets in per_split.items():
        total = sum(d["row_count"] for d in datasets.values())
        crisis = sum(d["crisis_flag_count"] for d in datasets.values())
        dup, dup_pct = (
            sum(int(d.get("duplicates", 0)) for d in datasets.values()),
            (
                sum(d["row_count"] * d.get("duplicate_pct", 0.0) for d in datasets.values())
                / max(total, 1)
            ),
        )
        crisis_pct = 100.0 * crisis / max(total, 1)
        lines.append(
            f"| {split} | {_fmt_int(total)} | {_fmt_int(crisis)} | "
            f"{crisis_pct:.2f}% | {_fmt_int(dup)} | {dup_pct:.2f}% |"
        )

    # Per-split, per-dataset sections.
    for split, datasets in per_split.items():
        lines.append(_md_section(f"Split: `{split}`", ""))
        for dataset, stats in datasets.items():
            lines.append(_md_section(f"Dataset: `{dataset}`", ""))
            lines.append(f"- Rows: **{_fmt_int(stats['row_count'])}**")
            lines.append(
                f"- Crisis-flagged: **{_fmt_int(stats['crisis_flag_count'])}** "
                f"({100.0 * stats['crisis_flag_count'] / max(stats['row_count'], 1):.2f}%)"
            )
            tl = stats["text_token_len"]
            cl = stats["text_char_len"]
            lines.append(
                f"- Text length (chars): mean {cl['mean']:.1f}, "
                f"p50 {cl['p50']:.0f}, p95 {cl['p95']:.0f}, max {cl['max']}"
            )
            lines.append(
                f"- Text length (tokens): mean {tl['mean']:.1f}, "
                f"p95 {tl['p95']:.0f}, max {tl['max']}"
            )

            miss = stats["missing"]
            miss_str = ", ".join(f"{k}={v}" for k, v in miss.items() if v) or "none"
            lines.append(f"- Missing values: {miss_str}")

            emo = stats["emotion_label_top"]
            if emo:
                lines.append("- Top `emotion_label` values:")
                for label, count in emo:
                    lines.append(f"  - `{label}`: {count}")
            multi = stats["emotion_labels_top"]
            if multi:
                lines.append("- Top multi-label `emotion_labels` (GoEmotions):")
                for label, count in multi:
                    lines.append(f"  - `{label}`: {count}")
            topics = stats["topic_top"]
            if topics:
                lines.append("- Top `topic` values:")
                for label, count in topics:
                    lines.append(f"  - `{label}`: {count}")

            cs = stats["crisis_source_breakdown"]
            if cs:
                lines.append("- Crisis source breakdown:")
                for source, count in cs:
                    lines.append(f"  - `{source}`: {count}")

    return "\n".join(lines) + "\n"


# ---------------------------------------------------------------------------
# Stage entrypoint
# ---------------------------------------------------------------------------

def run() -> Path:
    """Validate processed parquets and write the report. Returns report path."""
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)

    per_split: dict[str, dict[str, dict]] = {}
    critical: list[str] = []

    for split in ("train", "val", "test"):
        path = processed_path(split)
        if not path.exists():
            critical.append(f"Missing processed parquet: {path}")
            continue
        df = pd.read_parquet(path)

        # Per-dataset slice.
        per_ds: dict[str, dict] = {}
        for ds_name in ("go_emotions", "empathetic_dialogues", "suicide_depression"):
            sub = df.loc[df["dataset"] == ds_name].copy()
            if sub.empty:
                per_ds[ds_name] = {
                    "row_count": 0,
                    "missing": {},
                    "text_char_len": {"mean": 0.0, "p50": 0.0, "p95": 0.0, "max": 0},
                    "text_token_len": {"mean": 0.0, "p95": 0.0, "max": 0},
                    "emotion_label_top": [],
                    "emotion_labels_top": [],
                    "topic_top": [],
                    "crisis_flag_count": 0,
                    "crisis_source_breakdown": [],
                    "duplicates": 0,
                    "duplicate_pct": 0.0,
                }
                continue
            stats = _per_dataset_stats(sub)
            dups, dup_pct = _duplicate_stats(sub)
            stats["duplicates"] = dups
            stats["duplicate_pct"] = dup_pct
            if dup_pct > 0.05:
                critical.append(
                    f"[{split}/{ds_name}] duplicate ratio {dup_pct:.1%} > 5%"
                )
            per_ds[ds_name] = stats

        # Whole-split dup check.
        dups, dup_pct = _duplicate_stats(df)
        if dup_pct > 0.10:
            critical.append(
                f"[{split}] cross-dataset duplicate ratio {dup_pct:.1%} > 10%"
            )

        per_split[split] = per_ds

        # Sanity: empty split.
        if len(df) == 0:
            critical.append(f"[{split}] is empty")

    report_text = _build_report(per_split)
    out_path = report_path()
    out_path.write_text(report_text, encoding="utf-8")
    print(f"[validate] wrote {out_path}")

    if critical:
        msg = "CRITICAL issues found:\n  - " + "\n  - ".join(critical)
        raise RuntimeError(msg)
    return out_path


if __name__ == "__main__":
    run()
